### ISSUE TITLE
Cannot install through Dolphin's shopping service menu.

### ISSUE THREAD

**Issue by Impeta** [fabiomux/kde-servicemenus#13]
I wasn't able to make the downloading videos with yt-dlp project show up on my right-click pop-up, even as seemingly properly installed through aforementioned method with no errors. However, installing it as raw through cloning your repository, making it and installing it manually does make it show up finally.

Looks to be same exact issue as #6, interestingly enough.

**Comment by fabiomux** [comment]
Hello,
Just tried to install it from the Dolphin settings interface and it works for me, which version of Dolphin are you using?

Have you used the `servicemenuinstaller` command to install the archive? If so have you got some error messages?
