### ISSUE TITLE
How can I help translate "Open yakuake here"

### ISSUE THREAD

**Issue by adocampo** [fabiomux/kde-servicemenus#15]
As a hardcore user of yakuake I wonder why I didn't thought before about this, many times pressing F4 on Dolphin to launch a command but getting stuck if the command took a lot, like encoding videos, so I had to manually go to a path to continue, this service menu is just what I needed. So, thank you!

I have Plasma in Spanish and open yakuake here is mostly show in English,
![image](https://github.com/fabiomux/kde-servicemenus/assets/2266612/f143378d-fdcc-4c96-800a-faa2b486816d)

and one of the two translated sentences into Spanish is using the polite form instead of the infinitive, which is the form used in the entire desktop.
![image](https://github.com/fabiomux/kde-servicemenus/assets/2266612/40ea34ea-ea54-4ea2-8a92-a4d319e41028)
I would like to translate the missing strings and correct this one, but I didn't see how. Could you give me some instructions to help to do this? 

PS: I could translate this into Spanish and Catalan.

**Comment by fabiomux** [comment]
Hi Angel,

Inside the kde-servicemenus/open_yakuake_here folder there is the `.desktop` file which is a file in the ini format.
What you have to do is insert a `Name[es]` and `Name[ca]` underneath any other `Name` field in the several sections.

Thank you in advance!

**Comment by adocampo** [comment]
Great, it's here https://github.com/fabiomux/kde-servicemenus/pull/16

**Comment by fabiomux** [comment]
The update should be available in the Kde-store/Pling network, thanks again!
