### ISSUE TITLE
open_yakuake_here: fail at copy file to a non existing directory

### ISSUE THREAD

**Issue by noguxx** [fabiomux/kde-servicemenus#17]
sh install.sh --install
Starting procedure from install.sh
Parameters: 1
Parameter: --install
Installing: open_yakuake_here.desktop
cp: cannot create regular file '/home/xxxx/.local/share/kservices5/ServiceMenus/': No such file or directory
Service Menu installed!

It will work if I run:
mkdir -p  /home/xxxx/.local/share/kservices5/ServiceMenus

**Comment by fabiomux** [comment]
Just released a patch version, thank you again!
