### ISSUE TITLE
Install script for download_with_yt-dlp_here references download_with_youtube-dl_here.desktop

### ISSUE THREAD

**Issue by dsbrown** [fabiomux/kde-servicemenus#18]
The install.sh script, which I downloaded from here: https://store.kde.org/p/2012539 references:

     desktop_filename='download_with_youtube-dl_here.desktop'

instead of:

     desktop_filename='download_with_yt-dlp_here.desktop

Here is the diff of the original and the one I fixed:
```
diff download_with_yt-dlp_here/install.sh download_with_yt-dlp_here\(corrected\)/install.sh 
5c5
< desktop_filename='download_with_youtube-dl_here.desktop'
---
> desktop_filename='download_with_yt-dlp_here.desktop'
```

**Comment by fabiomux** [comment]
Thank you very much, I just reuploaded the archive, unfortunately, this morning I updated both the service and executed the Makefile using wildcards which ended up in this bad overwriting.
