### ISSUE TITLE
Newline character before file name

### ISSUE THREAD

**Issue by sicherist** [fabiomux/kde-servicemenus#20]
Hello and thank you for creating this add-on!
I use it mainly to copy the filename, and a few days ago the behavior changed:
Now every time I copy a file name, there is a new-line character in front of the file name. This is a problem when pasting into spreadsheets.
Is anyone else seeing this problem?

Unfortunately I don't know what software update caused this, maybe dolphin changed something?
I'm running Kubuntu 23.10, Dolphin 23.08.1

**Comment by fabiomux** [comment]
Added the 1.3.1-beta1 package in the KDE store, let me know if it is fixed :)

**Comment by sicherist** [comment]
Thank you very much! The beta-package fixed the issue. One other thing I noticed is that there is now always a "kdialog" popup, when I copy a filename. Is there a way to disable it?

**Comment by fabiomux** [comment]
Thanks to you @sicherist :),
 I am going to fix this one too, probably shutting it down by default and using a shell variable to turn it on again!

**Comment by fabiomux** [comment]
Added the 1.4.0-beta1, if everything works fine I will upload all of them as stable versions.

**Comment by sicherist** [comment]
Thank you very much, it works well! (I didn't test all the functions, just the "copy the name only"). In 1.4.0-beta1 there is no localization except Italian - I assume this is intentional?

**Comment by fabiomux** [comment]
Ah sorry, being in a rush I forgot to double-check the filename, anyway all the localizations are up now! :)
