### ISSUE TITLE
copy_to_clipper installed into wrong directory on plasma6

### ISSUE THREAD

**Issue by Termuellinator** [fabiomux/kde-servicemenus#21]
Hi again ;)

For Plasma6, the .desktop file needs to be located in `~/.local/share/kio/servicemenus/` but is still installed into `~/.local/share/kservices5/ServiceMenus/`. Otherwise it seems to work fine :+1:

**Comment by fabiomux** [comment]
Hi Termuellinator,

the last version should work exactly like that, do you have the qtpath6 command installed?

**Comment by Termuellinator** [comment]
I only have `qtpaths` as part of `qt6-base` and `qt5-base`, which are both installed. `which qtpaths` points to the qt5 version though. But that seems to not interfere:
```
> qtpaths --locate-dirs GenericDataLocation kio/servicemenus                                                                                                                                                                                                                         
/home/termy/.local/share/kio/servicemenus:/usr/share/kio/servicemenus
```

kf5-config is also still installed and yields 
```
> kf5-config --path services                                                                                                                                                                                                                                                    [130]
/home/termy/.local/share/kservices5/:/usr/share/kservices5/
```

I've removed `kf5-config` (as part of kdelibs4support) now, but `qt5-base` is still a dep for a lot of things. Of course i don't know if less manual distros than Arch automatically would've removed kf5-config while upgrading to plasma6?
Maybe it would be safer to put the qtpaths conditional before the kf5-config check?

**Comment by fabiomux** [comment]
> I've removed `kf5-config` (as part of kdelibs4support) now, but `qt5-base` is still a dep for a lot of things. Of course i don't know if less manual distros than Arch automatically would've removed kf5-config while upgrading to plasma6? Maybe it would be safer to put the qtpaths conditional before the kf5-config check?

Unfortunately *qtpaths* is present under Plasma 5 as well, evaluating it for first as it currently does, might be misleading for the old platform.

The best solution would be to put qtpaths6 on top, but if you don't have it by default I have to find another way to detect the  KDE version, maybe this one returns the correct number for you?
```shell
qtpaths --qt-version
```

**Comment by Termuellinator** [comment]
Nope, that returns 5.15.3.
`/usr/lib/qt6/bin/qtpaths --qt-version` yields the correct 6.7.0. Of course i don't know if that location is Arch specific.
But as you are using `command` for the check, i don't think that using this with the full path as the first conditional would have any adverse effects if it's not present in others distros, would it?

**Comment by fabiomux** [comment]
I am afraid that this command is bound to the libraries installed, and not to the specific DE, I have noticed
that I have qt6 libraries installed too, so checking for that particular folder in the path doesn't solve the problem.
Let's try this:
```shell
plasmashell -v
```

**Comment by Termuellinator** [comment]
```
> plasmashell -v                                                                                                                                                                                                                                                                     
plasmashell 6.0.4
```
Sounds like a good solution, at least if we can verify that this command already existed in Plasma 5 (which i would assume) :+1:

**Comment by fabiomux** [comment]
Great, I am going to implement it!

Yes, I can confirm that's on Plasma 5 too because it is my current DE. I won't strip off the other methods but will put it as the first case to check.

**Comment by fabiomux** [comment]
The 1.4.1-beta1 version is available to download, just in case you wan to give a try :-)

**Comment by Termuellinator** [comment]
It somehow doesn't work when installing it through the Dolphin interface (no feedback there at all), but `servicemenuinteraller` and `make install` work fine :+1: 
Don't know how to approach troubleshooting the GUI issue though tbh - other plugins installed just fine.

**Comment by fabiomux** [comment]
You can try starting Dolphin from Konsole and reading the outputs there while trying to install the service.

**Comment by Termuellinator** [comment]
Yeah, too much of a long weekend to have thought of that myself... :sweat_smile: 
But now it seems to work anyway, don't know what was up with that, maybe pling hadn't caught up yet or something like that?
So everything works now :+1:

**Comment by fabiomux** [comment]
Yes, most probably you had some problem with the server, but glad to know that everything is fixed :-)
