### ISSUE TITLE
Info: "Run all Konsole windows in a single process" must be unchecked.

### ISSUE THREAD

**Issue by electrotype** [fabiomux/kde-servicemenus#4]
Just an information: Konsole must not have the setting `General/Process and window/Run all Konsole windows in a single process` checked for your `open_konsole_here` script to work.

Otherwise, it works very well! Thank you!

**Comment by fabiomux** [comment]
Thanks for report, I will try to fix it

**Comment by electrotype** [comment]
You could also simply add a note, if you are unable to fix it easily, I think it's perfectly acceptable.

In fact, the only reason I had this option checked is because I was trying to make any new terminal to open in the already running Konsole instance! And I left it checked, for no reason. Then I found your extension. I'm not sure why someone would checked this option, to be honest... I guess there is a usecase, though.

Thanks again!

**Comment by fabiomux** [comment]
I think I found what changes between the two modes, seems a little bit tricky but feasible.
I don't know either why there is this option, the only difference seems in the D-Bus structure.

**Comment by fabiomux** [comment]
Uploaded the latest changes, now should work with or without this option selected.
