### ISSUE TITLE
Open Yakuake Here Auto install failed with dolphin's download new service

### ISSUE THREAD

**Issue by 4piu** [fabiomux/kde-servicemenus#6]
I tried to install the "Open Yakuake here" plugin with the download new stuff feature: 

Settings > Configure Dolphin > Context Menu > Download new services

When installing, a konsole pop up with an error:

```
Starting procedure from install.sh
No parameters, try --install or --uninstall

~/.l/sh/se/open_yakuake_here-1.0.2.tgz-dir/open_yakuake_here:
```

However, I successfully installed the plugin by executing `make install`

```
~/.l/sh/se/o/open_yakuake_here: make install

sh install.sh --install
Starting procedure from install.sh
Parameters: 1
Parameter: --install
Installing: open_yakuake_here.desktop
Service Menu installed!
```

**Comment by 4piu** [comment]
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.2
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.15.25-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1060/PCIe/SSE2

**Comment by fabiomux** [comment]
Updated on the Pling repo too!

**Comment by 4piu** [comment]
I have tested and it was installed without issue. Thanks again for your hard work!

**Comment by fabiomux** [comment]
@4piu Thanks to you for using it and reporting the issue :-)
